<?php

namespace ApiBundle\Repository;

/**
 * GeneralInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeneralInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
