<?php

namespace ApiBundle\Repository;

/**
 * SlopeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlopeRepository extends \Doctrine\ORM\EntityRepository
{
}
